/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VultureSoftware;

import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JPanel;


/**
 *
 * @author jamie2
 */
public class DashBoardUI extends javax.swing.JFrame {

    /**
     * Creates new form DashBoardUI
     * @param role
     */
    
    private static String role;
    public DashBoardUI(String role) {
        initComponents();
        this.role = role;
        System.out.println(role);
        setButtons(role);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        finalInspectionButton = new javax.swing.JButton();
        currentJobsButton = new javax.swing.JButton();
        jobDelayButton = new javax.swing.JButton();
        orderPartsButton = new javax.swing.JButton();
        adminButton = new javax.swing.JButton();
        graphButton = new javax.swing.JButton();
        taskAllocatorButton = new javax.swing.JButton();
        newCustomerButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jPanel2.setBackground(new java.awt.Color(102, 153, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 730, 60));

        finalInspectionButton.setBackground(new java.awt.Color(102, 153, 255));
        finalInspectionButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        finalInspectionButton.setForeground(new java.awt.Color(255, 255, 255));
        finalInspectionButton.setText("Final Inspection");
        finalInspectionButton.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)));
        finalInspectionButton.setFocusable(false);
        finalInspectionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finalInspectionButtonfinaIinspectActionPerformed(evt);
            }
        });
        jPanel2.add(finalInspectionButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, 180, 50));

        currentJobsButton.setBackground(new java.awt.Color(102, 153, 255));
        currentJobsButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        currentJobsButton.setForeground(new java.awt.Color(255, 255, 255));
        currentJobsButton.setText("Current jobs");
        currentJobsButton.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)));
        currentJobsButton.setFocusable(false);
        currentJobsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currentJobsButtonActionPerformed(evt);
            }
        });
        jPanel2.add(currentJobsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 80, 180, 50));

        jobDelayButton.setBackground(new java.awt.Color(102, 153, 255));
        jobDelayButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jobDelayButton.setForeground(new java.awt.Color(255, 255, 255));
        jobDelayButton.setText("Delay a job");
        jobDelayButton.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)));
        jobDelayButton.setFocusable(false);
        jobDelayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jobDelayButtonActionPerformed(evt);
            }
        });
        jPanel2.add(jobDelayButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 180, 50));

        orderPartsButton.setBackground(new java.awt.Color(102, 153, 255));
        orderPartsButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        orderPartsButton.setForeground(new java.awt.Color(255, 255, 255));
        orderPartsButton.setText("Order new parts");
        orderPartsButton.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)));
        orderPartsButton.setFocusable(false);
        orderPartsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderPartsButtonActionPerformed(evt);
            }
        });
        jPanel2.add(orderPartsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 180, 50));

        adminButton.setBackground(new java.awt.Color(102, 153, 255));
        adminButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        adminButton.setForeground(new java.awt.Color(255, 255, 255));
        adminButton.setText("Admin");
        adminButton.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)));
        adminButton.setFocusable(false);
        adminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminButtonActionPerformed(evt);
            }
        });
        jPanel2.add(adminButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 290, 180, 50));

        graphButton.setBackground(new java.awt.Color(102, 153, 255));
        graphButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        graphButton.setForeground(new java.awt.Color(255, 255, 255));
        graphButton.setText("Statistics graphs");
        graphButton.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)));
        graphButton.setFocusable(false);
        graphButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                graphButtonActionPerformed(evt);
            }
        });
        jPanel2.add(graphButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 180, 180, 50));

        taskAllocatorButton.setBackground(new java.awt.Color(102, 153, 255));
        taskAllocatorButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        taskAllocatorButton.setForeground(new java.awt.Color(255, 255, 255));
        taskAllocatorButton.setText("Task Allocator");
        taskAllocatorButton.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)));
        taskAllocatorButton.setFocusable(false);
        taskAllocatorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taskAllocatorButtonActionPerformed(evt);
            }
        });
        jPanel2.add(taskAllocatorButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 180, 50));

        newCustomerButton.setBackground(new java.awt.Color(102, 153, 255));
        newCustomerButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        newCustomerButton.setForeground(new java.awt.Color(255, 255, 255));
        newCustomerButton.setText("New Customer Account");
        newCustomerButton.setActionCommand("New customer account");
        newCustomerButton.setAlignmentX(0.5F);
        newCustomerButton.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)));
        newCustomerButton.setFocusable(false);
        newCustomerButton.setMaximumSize(new java.awt.Dimension(165, 27));
        newCustomerButton.setMinimumSize(new java.awt.Dimension(165, 27));
        newCustomerButton.setOpaque(false);
        newCustomerButton.setPreferredSize(new java.awt.Dimension(165, 27));
        newCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newCustomerButtonActionPerformed(evt);
            }
        });
        jPanel2.add(newCustomerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 180, 50));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jobDelayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jobDelayButtonActionPerformed
        // TODO add your handling code here:
       new JobDelayUI().setVisible(true);
    }//GEN-LAST:event_jobDelayButtonActionPerformed

    private void orderPartsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderPartsButtonActionPerformed
        // TODO add your handling code here:
        new OrderPartsUI().setVisible(true);
    }//GEN-LAST:event_orderPartsButtonActionPerformed

    private void currentJobsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currentJobsButtonActionPerformed
        // TODO add your handling code here:
        new CurrentJobsUI().setVisible(true);
    }//GEN-LAST:event_currentJobsButtonActionPerformed

    private void graphButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_graphButtonActionPerformed
        // TODO add your handling code here:
        new ViewGraphUI().setVisible(true);
    }//GEN-LAST:event_graphButtonActionPerformed

    private void adminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminButtonActionPerformed
        // TODO add your handling code here:
        new AdminUI().setVisible(true);
    }//GEN-LAST:event_adminButtonActionPerformed

    private void finalInspectionButtonfinaIinspectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalInspectionButtonfinaIinspectActionPerformed
        new FinalInspectionUI().setVisible(true);
    }//GEN-LAST:event_finalInspectionButtonfinaIinspectActionPerformed

    private void taskAllocatorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taskAllocatorButtonActionPerformed
        // TODO add your handling code here:
        new TaskAllocatorUI().setVisible(true);
    }//GEN-LAST:event_taskAllocatorButtonActionPerformed

    private void newCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newCustomerButtonActionPerformed
        // TODO add your handling code here:
        new NewCustomerAccountUI().setVisible(true);
    }//GEN-LAST:event_newCustomerButtonActionPerformed
     
    
    private void setButtons(String role)
    {
        if(role.toLowerCase().equals("tech"))
        {
            adminButton.setEnabled(false);
            newCustomerButton.setEnabled(false);
            jobDelayButton.setEnabled(false);
            taskAllocatorButton.setEnabled(false);
            orderPartsButton.setEnabled(false);
            graphButton.setEnabled(false);
            //needs current jobs
            
        }
        if(role.toLowerCase().equals("collection and delivery"))
        {
            adminButton.setEnabled(false);
            jobDelayButton.setEnabled(false);
            newCustomerButton.setEnabled(false);
            taskAllocatorButton.setEnabled(false);
            orderPartsButton.setEnabled(false);
            graphButton.setEnabled(false);
            //needs current jobs
        }
        if(role.toLowerCase().equals("finance"))
        {
            adminButton.setEnabled(false);
            jobDelayButton.setEnabled(false);
            newCustomerButton.setEnabled(false);
            taskAllocatorButton.setEnabled(false);
            orderPartsButton.setEnabled(false);
            currentJobsButton.setEnabled(false);
            //needs stats graphs
        }
        if(role.toLowerCase().equals("customer support"))
        {
            adminButton.setEnabled(false);
            jobDelayButton.setEnabled(false);		
            orderPartsButton.setEnabled(false);
            currentJobsButton.setEnabled(false);
            graphButton.setEnabled(false);
            //needs create new customer account + new job
        }
        if(role.toLowerCase().equals("resource"))
        {
            adminButton.setEnabled(false);
            currentJobsButton.setEnabled(false);
            graphButton.setEnabled(false);
            newCustomerButton.setEnabled(false);
            taskAllocatorButton.setEnabled(false);
            //needs order new parts + delay job
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashBoardUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashBoardUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashBoardUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashBoardUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashBoardUI(role).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminButton;
    private javax.swing.JButton currentJobsButton;
    private javax.swing.JButton finalInspectionButton;
    private javax.swing.JButton graphButton;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jobDelayButton;
    private javax.swing.JButton newCustomerButton;
    private javax.swing.JButton orderPartsButton;
    private javax.swing.JButton taskAllocatorButton;
    // End of variables declaration//GEN-END:variables
}
