/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VultureSoftware;

import databaseui.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Jordan 17012215
 */
public class MotorEditUI extends javax.swing.JFrame {

    /**
     * Creates new form MotorEditUI
     */
    static DataBaseToolkit dbtk;
    static ArrayList<JobObject> job;
    
    public MotorEditUI(ArrayList job, DataBaseToolkit dbtk) 
    {
        initComponents();
        this.dbtk = dbtk;
        this.job = job;
        
        setFields();
    }

    /**
     * This method is called from within the constructor to initialise the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        JTFMotorName = new javax.swing.JTextField();
        titleLabel = new javax.swing.JLabel();
        JTFDateCollected = new javax.swing.JTextField();
        collectedLabel = new javax.swing.JLabel();
        JTFClient = new javax.swing.JTextField();
        clientLabel = new javax.swing.JLabel();
        JTFEstimated = new javax.swing.JTextField();
        estimateLabel = new javax.swing.JLabel();
        JTFChecked = new javax.swing.JTextField();
        checkLabel = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        manufacturerLabel = new javax.swing.JLabel();
        returnLabel = new javax.swing.JLabel();
        JTFReturnDate = new javax.swing.JTextField();
        partsLabel = new javax.swing.JLabel();
        TAParts = new java.awt.TextArea();
        JCBMan = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(175, 0));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));

        nameLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(255, 255, 255));
        nameLabel.setText("Motor Name");

        JTFMotorName.setNextFocusableComponent(JTFDateCollected);

        titleLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel.setText("Edit Job");

        JTFDateCollected.setNextFocusableComponent(JTFEstimated);
        JTFDateCollected.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JTFDateCollectedMousePressed(evt);
            }
        });

        collectedLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        collectedLabel.setForeground(new java.awt.Color(255, 255, 255));
        collectedLabel.setText("Date Collected");

        clientLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        clientLabel.setForeground(new java.awt.Color(255, 255, 255));
        clientLabel.setText("Client");

        JTFEstimated.setNextFocusableComponent(TAParts);

        estimateLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        estimateLabel.setForeground(new java.awt.Color(255, 255, 255));
        estimateLabel.setText("Estimated Hours");

        checkLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        checkLabel.setForeground(new java.awt.Color(255, 255, 255));
        checkLabel.setText("Checked By");

        saveButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        saveButton.setText("Update Job");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        manufacturerLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        manufacturerLabel.setForeground(new java.awt.Color(255, 255, 255));
        manufacturerLabel.setText("Manufacturer");

        returnLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        returnLabel.setForeground(new java.awt.Color(255, 255, 255));
        returnLabel.setText("Return Date");

        JTFReturnDate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JTFReturnDateMousePressed(evt);
            }
        });

        partsLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        partsLabel.setForeground(new java.awt.Color(255, 255, 255));
        partsLabel.setText("Parts Needed");

        JCBMan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JCBMan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Actiro", "Buhler", "PG", "Other" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(partsLabel))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(estimateLabel)))
                        .addComponent(manufacturerLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(checkLabel, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JTFEstimated, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTFChecked, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TAParts, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(JTFMotorName, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(JCBMan, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(titleLabel)
                                .addGap(432, 432, 432))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(377, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(clientLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(JTFClient, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(returnLabel)
                                    .addComponent(collectedLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JTFDateCollected, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JTFReturnDate, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(109, 109, 109))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(193, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(JTFMotorName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nameLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JCBMan, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(manufacturerLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JTFEstimated, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(estimateLabel))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JTFChecked, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(checkLabel)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JTFClient, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clientLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JTFDateCollected, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(collectedLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(returnLabel)
                            .addComponent(JTFReturnDate, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TAParts, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(partsLabel))
                .addGap(9, 9, 9))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
               //dbtk.closeConnectionToDB();
        trim();
        if (checks() && checkHours(JTFEstimated.getText()) ) {
            
            //if both fields are edited
            if (!JTFDateCollected.getText().equals("DD/MM/YYYY") && !JTFReturnDate.getText().equals("DD/MM/YYYY")) 
            {
                if (!checkDate(JTFDateCollected.getText() ) && !checkDate(JTFReturnDate.getText() ) )
                {
                  JOptionPane.showMessageDialog(null, "Format for date fields must be DD/MM/YYYY", "", JOptionPane.INFORMATION_MESSAGE);
                }
                else
                    {
                        //System.out.println("update 1");
                        update();
                        this.dispose();
                    }                
            }
            
            //only date collected is edited
            else if(!JTFDateCollected.getText().equals("DD/MM/YYYY") && JTFReturnDate.getText().equals("DD/MM/YYYY"))
            {
                if (!checkDate(JTFDateCollected.getText() )){
                    JOptionPane.showMessageDialog(null, "Format is incorrect for date collected. Must be DD/MM/YYYY", "", JOptionPane.INFORMATION_MESSAGE);
                }
                else{
                    //System.out.println("update 2");
                        update();
                        this.dispose();
                }
            }
            //only return date edited
            else if(JTFDateCollected.getText().equals("DD/MM/YYYY") && !JTFReturnDate.getText().equals("DD/MM/YYYY"))
            {
                if (!checkDate(JTFReturnDate.getText() )){
                    JOptionPane.showMessageDialog(null, "Format is incorrect for return date. Must be DD/MM/YYYY", "", JOptionPane.INFORMATION_MESSAGE);
                }
                else{
                    //System.out.println("update 3");
                        update();
                        this.dispose();
                }
            }
            //neither edited
            else
            {
                //System.out.println("update 4");
                        update();
                        this.dispose();
            }
        }              
    
        
       

        
    }//GEN-LAST:event_saveButtonActionPerformed

    private void JTFDateCollectedMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTFDateCollectedMousePressed
        if(JTFDateCollected.getText().equals("DD/MM/YYYY")){
            JTFDateCollected.setText("");
        };
    }//GEN-LAST:event_JTFDateCollectedMousePressed

    private void JTFReturnDateMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTFReturnDateMousePressed
        if(JTFReturnDate.getText().equals("DD/MM/YYYY")){
            JTFReturnDate.setText("");
        }
    }//GEN-LAST:event_JTFReturnDateMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MotorEditUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MotorEditUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MotorEditUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MotorEditUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MotorEditUI(job, dbtk).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> JCBMan;
    private javax.swing.JTextField JTFChecked;
    private javax.swing.JTextField JTFClient;
    private javax.swing.JTextField JTFDateCollected;
    private javax.swing.JTextField JTFEstimated;
    private javax.swing.JTextField JTFMotorName;
    private javax.swing.JTextField JTFReturnDate;
    private java.awt.TextArea TAParts;
    private javax.swing.JLabel checkLabel;
    private javax.swing.JLabel clientLabel;
    private javax.swing.JLabel collectedLabel;
    private javax.swing.JLabel estimateLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel manufacturerLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel partsLabel;
    private javax.swing.JLabel returnLabel;
    private javax.swing.JButton saveButton;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables


//textArea1.setLineWrap(true);
//textArea1.setWrapStyleWord(true);
public void setFields()
{
    JTFMotorName.setText(job.get(0).getJobMotorName());    
    JTFChecked.setText(job.get(0).getJobCheckBy());
    JTFEstimated.setText(""+job.get(0).getJobExpectedTime());
    JTFDateCollected.setText(job.get(0).getJobDateCollected());
    TAParts.setText(job.get(0).getJobParts());
    JTFClient.setText(job.get(0).getJobClient());
    JTFReturnDate.setText(job.get(0).getJobReturnDate());
    JTFChecked.setText(job.get(0).getJobCheckBy());  
    
    dbtk.closeConnectionToDB();
    
                    
}

private void trim(){
        String textMN = JTFMotorName.getText().trim();
        JTFMotorName.setText(textMN);
        String textE = JTFEstimated.getText().trim();
        JTFEstimated.setText(textE);
        String textP = TAParts.getText().trim();
        TAParts.setText(textP);
        String textCh = JTFChecked.getText().trim();
        JTFChecked.setText(textCh);
        String textCl = JTFClient.getText().trim();
        JTFClient.setText(textCl);
        String textDC = JTFDateCollected.getText().trim();
        JTFDateCollected.setText(textDC);
        String textRD = JTFReturnDate.getText().trim();
        JTFReturnDate.setText(textRD);

        //set text field to default if left blank
        if (JTFDateCollected.getText().equals("")) {
            JTFDateCollected.setText("DD/MM/YYYY");
        }
        if (JTFReturnDate.getText().equals("")) {
            JTFReturnDate.setText("DD/MM/YYYY");
        }
        if (JTFClient.getText().equals("")) {
            JTFClient.setText(null);
        }
}

private boolean checks() {
        
    
    
    if (JTFMotorName.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please enter the name of the motor", "", JOptionPane.INFORMATION_MESSAGE);
            return false;
        } else if (JCBMan.getSelectedItem().equals("Select a manufacturer")) {
            JOptionPane.showMessageDialog(null, "Please select a manufacturer from the drop down menu", "", JOptionPane.INFORMATION_MESSAGE);
            return false;
        } else if (JTFEstimated.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please enter estimated working hours required", "", JOptionPane.INFORMATION_MESSAGE);
            return false;
        } else if (JTFChecked.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please enter the name of who checked this motor", "", JOptionPane.INFORMATION_MESSAGE);
            return false;
        } else if (TAParts.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please enter the parts required", "", JOptionPane.INFORMATION_MESSAGE);
            return false;
        } 
        else {
            return true;
        }
    }

private void update() {

        int jobNo = job.get(0).getJobNumber();
        String motorName = JTFMotorName.getText();
        String dateCollected = JTFDateCollected.getText();
        String estimatedHours = JTFEstimated.getText();
        String partsNeeded = TAParts.getText();
        String checkedBy = JTFChecked.getText();
        String client = JTFClient.getText();
        String manufacturer = (String)JCBMan.getSelectedItem();
        String returnDate = JTFReturnDate.getText();
        
        if (dbtk.updateJob(jobNo, motorName, dateCollected, partsNeeded, client, manufacturer, returnDate, checkedBy, estimatedHours)) {
            JOptionPane.showMessageDialog(null, "Successfully updated job: " + motorName, "Success", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
            //CurrentJobsUI.setJobList(); to refresh on add. static context error
        } else {
            JOptionPane.showMessageDialog(null, "Failed to update database", "Error", JOptionPane.ERROR_MESSAGE); 
            this.dispose();
        }
    }

private boolean checkDate(String date) {
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        try {
            dateFormat.parse(date.trim());

        } catch (ParseException pe) {
            return false;
        }
        return true;
    }

private boolean checkHours(String hours){
         int result;
         try{
         result = Integer.parseInt(hours);	
         }
         catch(Exception e){
             JOptionPane.showMessageDialog(null, "Must enter a valid amount of hours", "Error", JOptionPane.ERROR_MESSAGE);
             return false;
         }
         if(result < 100 ){
             return true;
         }
         else{
            JOptionPane.showMessageDialog(null, "Must enter a valid amount of hours", "Error", JOptionPane.ERROR_MESSAGE);
             return false;
         }
         
     }
}